apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: logs-kafka
  namespace: kafka
spec:
  template:
    metadata:
      labels:
        k8s-app: logs-kafka
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: kafkacat
        image: solsson/kafkacat@sha256:ebebf47061300b14a4b4c2e1e4303ab29f65e4b95d34af1b14bb8f7ec6da7cef
        command:
        - sh
        - -ec
        - >
          cd /var/log/containers/;
          tail
          -n 0
          --follow=name
          *.log
          |
          kafkacat
          -b kafka-0.broker.kafka.svc.cluster.local:9092,kafka-1.broker.kafka.svc.cluster.local:9092,kafka-2.broker.kafka.svc.cluster.local:9092
          -t ops-kube-logs-raw-001
          -P
          #-z snappy
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
