# A headless service to create DNS records
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: broker
spec:
  ports:
  # [podname].broker.default.svc.cluster.local
  clusterIP: None
  selector:
    app: kafka
