apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: kafka-1
  namespace: kafka
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
        petindex: "1"
    spec:
      containers:
      - name: broker
        image: solsson/kafka-persistent:0.10.1
        #resources:
        #  requests:
        #    cpu: 100m
        #    memory: 100Mi
        ports:
          - containerPort: 9092
        command:
          - ./bin/kafka-server-start.sh
          - config/server.properties
          - --override
          - broker.id=1
          - --override
          - advertised.listeners=PLAINTEXT://broker-1.kafka.svc.cluster.local:9092
        volumeMounts:
          - name: datadir
            mountPath: /opt/kafka/data
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: datadir-kafka-1
