apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: schemas
  namespace: kafka
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
      - name: cp
        image: solsson/kafka-cp@sha256:a22047b9e8bf4b8badfd2fbba47f2d1acdcbb84dfb03c61a15e1ac203036cedf
        command:
        - schema-registry-start
        - /etc/schema-registry/schema-registry.properties
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/schema-registry
      volumes:
      - name: config
        configMap:
          name: confluent-config
