apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rest
  namespace: kafka
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-rest
    spec:
      containers:
      - name: cp
        image: solsson/kafka-cp@sha256:53075cf5877c1311516d5c78a4d52fd46d3d369514681e150f96bc06997fa0e4
        env:
        # what does this do?
        - name: KAFKA_REST_HOST_NAME
          value: rest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/kafka-rest
      volumes:
      - name: config
        configMap:
          name: confluent-config
