apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rest
  namespace: kafka
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-rest
    spec:
      containers:
      - name: cp-kafka-rest
        image: confluentinc/cp-kafka-rest@sha256:aa213c1a67eae6ce9836b52a9b5ecee4d6a0b44f2b9cc69f4e4de85131462f1d
        env:
        - name: KAFKA_REST_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: KAFKA_REST_HOST_NAME
          value: rest
        - name: KAFKA_REST_LISTENERS
          value: http://0.0.0.0:80
        - name: KAFKA_REST_SCHEMA_REGISTRY_URL
          value: http://schemas.kafka.svc.cluster.local:80
        ports:
        - containerPort: 80
