---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: logs-kafka
  annotations:
    manifest-origin: 'github.com/Yolean/kubernetes-kafka'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: filebeat-sa-view
  namespace: logs-kafka
  annotations:
    manifest-origin: 'github.com/Yolean/kubernetes-kafka'
subjects:
- kind: ServiceAccount
  name: filebeat
  namespace: logs-kafka
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
