---
apiVersion: extensions/v1beta1
description: Kubernetes Native Serverless Framework
kind: ThirdPartyResource
metadata:
  name: function.k8s.io
versions:
- name: v1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-acct
  namespace: kubeless
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    kubeless: controller
  name: kubeless-controller
  namespace: kubeless
spec:
  selector:
    matchLabels:
      kubeless: controller
  template:
    metadata:
      labels:
        kubeless: controller
    spec:
      containers:
      - image: bitnami/kubeless-controller@sha256:0bc030762e8694d268be75bed0d52ea6ecb84b03da85ffcbd55da4817c047052
        imagePullPolicy: IfNotPresent
        name: kubeless-controller
      serviceAccountName: controller-acct
