apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ksql
  namespace: kafka
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: ksql
    spec:
      containers:
      - name: cp
        image: solsson/kafka-ksql@sha256:cea326dd042c4451d0c503d1ee2666d1fa893008acf20b9fb2bc0b2327fc23fb
        readinessProbe:
          httpGet:
            path: /
            port: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/ksql-rest-app
      volumes:
      - name: config
        configMap:
          name: ksql-config
